// <auto-generated />
using AcdYoklama.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcdYoklama.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20240229204508_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AcdYoklama.Models.DbEntities.Employee", b =>
                {
                    b.Property<int>("OgrenciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciId"));

                    b.Property<string>("Ogrenci_adi")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ogrenci_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ogrenci_sinif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ogrenci_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OgrenciId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("AcdYoklama.Models.DbEntities.Yoklama", b =>
                {
                    b.Property<int>("YoklamaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YoklamaId"));

                    b.Property<string>("Ders_adi")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ders_konusu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ders_ogrencileri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ders_ogretmeni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ders_saati")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YoklamaId");

                    b.ToTable("Yoklama");
                });
#pragma warning restore 612, 618
        }
    }
}
